### ISSUE TITLE
Plone 4 documentation training

### ISSUE THREAD

**Issue by avoinea** [collective/training_buildout#8]
If you follow the instalation instruction here: https://training.plone.org/4/plone_training_config/instructions.html section **Installing Plone without vagrant** you'll end up with a Plone 5 setup.

To fix, please add:

```
git checkout -b plone4 origin/plone4
```
after ```$ git clone https://github.com/collective/training_buildout.git buildout```

**Comment by avoinea** [comment]
Actually plone4 branch doesn't work. Even it is says it's vagrant free, I get this error:

```
An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/joint/sandbox/training_buildout/eggs/zc.buildout-2.5.2-py2.7.egg/zc/buildout/buildout.py", line 1995, in main
    getattr(buildout, command)(args)
  File "/joint/sandbox/training_buildout/eggs/zc.buildout-2.5.2-py2.7.egg/zc/buildout/buildout.py", line 666, in install
    installed_files = self[part]._call(recipe.install)
  File "/joint/sandbox/training_buildout/eggs/zc.buildout-2.5.2-py2.7.egg/zc/buildout/buildout.py", line 1410, in _call
    return f()
  File "/joint/sandbox/training_buildout/eggs/plone.recipe.zope2instance-4.2.14-py2.7.egg/plone/recipe/zope2instance/__init__.py", line 110, in install
    self.build_zope_conf()
  File "/joint/sandbox/training_buildout/eggs/plone.recipe.zope2instance-4.2.14-py2.7.egg/plone/recipe/zope2instance/__init__.py", line 385, in build_zope_conf
    file_storage, blob_storage, base_dir, var_dir, zlib)
  File "/joint/sandbox/training_buildout/eggs/plone.recipe.zope2instance-4.2.14-py2.7.egg/plone/recipe/zope2instance/__init__.py", line 743, in render_file_storage
    os.makedirs(file_storage_dir)
  File "/joint/sandbox/training_buildout/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/joint/sandbox/training_buildout/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/joint/sandbox/training_buildout/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/home/vagrant'
```

**Comment by pbauer** [comment]
Should be fixed now. I udated quite a lot. Can you try again?

**Comment by pbauer** [comment]
I updated the code and the docs but the plone4-branch seems to refuse being deployed to since travis is ultra-slow today. 
It is deployed to http://plone-training.readthedocs.io/en/plone4 but not to http://training.plone.org/4

**Comment by avoinea** [comment]
Yap. It works now. Tks!
